package com.pmo.pmoitserv.Model;
// Generated 27 juil. 2016 12:16:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
/**
 * Compte generated by hbm2java
 */
@Entity
@Table( name ="compte" )
public class Compte  implements java.io.Serializable {

     @Id
     @Column(name="idCompte")
     @GeneratedValue
     private int idCompte;
     @Column(name="CompteNom")
     private String compteNom;

    
     
     @Column(name="CompteAdresse")
     private String compteAdresse;
     
     @Column(name="CompteEmail")
     private String compteEmail;
     
     @Column(name="CompteTel")
     private String compteTel;
     
     @Column(name="CompteLogolien")
     private String compteLogolien;
     
      @Column(name="CompteFblien")
     private String compteFblien;
      
     @Column(name="CompteInlien")
     private String compteInlien;
     
     
     @ManyToMany(mappedBy="comptes", fetch=FetchType.EAGER)
     private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);
     
     @OneToMany(mappedBy="compte")
     private Set<Projet> projets = new HashSet<Projet>(0);
     
     @ManyToMany(mappedBy="comptes")
     private Set<Partenaire> partenaires = new HashSet<Partenaire>(0);

    public Compte() {
    }

	
    public Compte(int idCompte) {
        this.idCompte = idCompte;
    }
    public Compte(int idCompte, String compteNom, Set<Utilisateur> utilisateurs, Set<Projet> projets, Set<Partenaire> partenaires) {
       this.idCompte = idCompte;
       this.compteNom = compteNom;
       this.utilisateurs = utilisateurs;
       this.projets = projets;
       this.partenaires = partenaires;
    }

    public Compte(int idCompte, String compteNom, String compteAdresse, String compteEmail, String compteTel, String compteLogolien , Set<Utilisateur> utilisateurs, Set<Projet> projets, Set<Partenaire> partenaires) {
        this.idCompte = idCompte;
        this.compteNom = compteNom;
        this.compteAdresse = compteAdresse;
        this.compteEmail = compteEmail;
        this.compteTel = compteTel;
        this.compteLogolien = compteLogolien;
        this.utilisateurs = utilisateurs;
       this.projets = projets;
       this.partenaires = partenaires;
    }

    public Compte(int idCompte, String compteNom, String compteAdresse, String compteEmail, String compteTel, String compteLogolien, String compteFblien, String compteInlien, Set<Utilisateur> utilisateurs, Set<Projet> projets, Set<Partenaire> partenaires) {
        this.idCompte = idCompte;
        this.compteNom = compteNom;
        this.compteAdresse = compteAdresse;
        this.compteEmail = compteEmail;
        this.compteTel = compteTel;
        this.compteLogolien = compteLogolien;
        this.compteFblien = compteFblien;
        this.compteInlien = compteInlien;
        this.utilisateurs = utilisateurs;
       this.projets = projets;
       this.partenaires = partenaires;
    }
    
    
   
    public int getIdCompte() {
        return this.idCompte;
    }
    
    public void setIdCompte(int idCompte) {
        this.idCompte = idCompte;
    }
    public String getCompteNom() {
        return this.compteNom;
    }
    
    public void setCompteNom(String compteNom) {
        this.compteNom = compteNom;
    }
    
    public String getCompteAdresse() {
        return compteAdresse;
    }

    public void setCompteAdresse(String compteAdresse) {
        this.compteAdresse = compteAdresse;
    }

    public String getCompteEmail() {
        return compteEmail;
    }

    public void setCompteEmail(String compteEmail) {
        this.compteEmail = compteEmail;
    }

    public String getCompteTel() {
        return compteTel;
    }

    public void setCompteTel(String compteTel) {
        this.compteTel = compteTel;
    }

    public String getCompteLogolien() {
        return compteLogolien;
    }

    public void setCompteLogolien(String compteLogolien) {
        this.compteLogolien = compteLogolien;
    }

    public String getCompteFblien() {
        return compteFblien;
    }

    public void setCompteFblien(String compteFblien) {
        this.compteFblien = compteFblien;
    }

    public String getCompteInlien() {
        return compteInlien;
    }

    public void setCompteInlien(String compteInlien) {
        this.compteInlien = compteInlien;
    }
    
    
    
    public Set<Utilisateur> getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
        this.utilisateurs = utilisateurs;
    }
    public Set<Projet> getProjets() {
        return this.projets;
    }
    
    public void setProjets(Set<Projet> projets) {
        this.projets = projets;
    }
    public Set<Partenaire> getPartenaires() {
        return this.partenaires;
    }
    
    public void setPartenaires(Set<Partenaire> partenaires) {
        this.partenaires = partenaires;
    }




}


