package com.pmo.pmoitserv.Model;
// Generated 27 juil. 2016 12:16:57 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
/**
 * Projet generated by hbm2java
 */
@Entity
@Table(name="projet")
public class Projet  implements java.io.Serializable {


     @Id
     @Column(name="idProjet")
     @GeneratedValue
     private int idProjet;
     @ManyToOne
     @JoinColumn(name="compte_idCompte")
     private Compte compte;
     
     @Column(name="ProjetLabel")
     private String projetLabel;
     
     @Column(name="ProjetStatut")
     private String projetStatut;
     
     @Column(name="ProjetDteDebut")
     @Temporal(javax.persistence.TemporalType.DATE)
     private Date projetDteDebut;
     
     @Column(name="ProjetDteCloture")
     @Temporal(javax.persistence.TemporalType.DATE)
     private Date projetDteCloture;
     
     @Column(name="ProjetConcept")
     private String projetConcept;
     
     @OneToMany(mappedBy="projet")
     private Set<Risque> risques = new HashSet<Risque>(0);
     
     @OneToMany(mappedBy="projet")
     private Set<Demande> demandes = new HashSet<Demande>(0);
     
     @OneToMany(mappedBy="projet")
     private Set<Sousprojet> sousprojets = new HashSet<Sousprojet>(0);
     
     @OneToMany(mappedBy="projet")
     private Set<Pointsus> pointsuses = new HashSet<Pointsus>(0);

    public Projet() {
    }

	
    public Projet(int idProjet, Compte compte) {
        this.idProjet = idProjet;
        this.compte = compte;
    }
    public Projet(int idProjet, Compte compte, String projetLabel, Set<Risque> risques, Set<Demande> demandes, Set<Sousprojet> sousprojets, Set<Pointsus> pointsuses) {
       this.idProjet = idProjet;
       this.compte = compte;
       this.projetLabel = projetLabel;
       this.risques = risques;
       this.demandes = demandes;
       this.sousprojets = sousprojets;
       this.pointsuses = pointsuses;
    }

    public Projet(int idProjet, Compte compte, String projetLabel, String projetStatut, Date projetDteDebut, Date projetDteCloture, String projetConcept, Set<Risque> risques, Set<Demande> demandes, Set<Sousprojet> sousprojets, Set<Pointsus> pointsuses) {
        this.idProjet = idProjet;
        this.compte = compte;
        this.projetLabel = projetLabel;
        this.projetStatut = projetStatut;
        this.projetDteDebut = projetDteDebut;
        this.projetDteCloture = projetDteCloture;
        this.projetConcept = projetConcept;
        this.risques = risques;
       this.demandes = demandes;
       this.sousprojets = sousprojets;
       this.pointsuses = pointsuses;
    }
    
    
   
    public int getIdProjet() {
        return this.idProjet;
    }
    
    public void setIdProjet(int idProjet) {
        this.idProjet = idProjet;
    }
    public Compte getCompte() {
        return this.compte;
    }
    
    public void setCompte(Compte compte) {
        this.compte = compte;
    }
    public String getProjetLabel() {
        return this.projetLabel;
    }
    
    public void setProjetLabel(String projetLabel) {
        this.projetLabel = projetLabel;
    }

    public String getProjetStatut() {
        return projetStatut;
    }

    public void setProjetStatut(String projetStatut) {
        this.projetStatut = projetStatut;
    }

    public Date getProjetDteDebut() {
        return projetDteDebut;
    }

    public void setProjetDteDebut(Date projetDteDebut) {
        this.projetDteDebut = projetDteDebut;
    }

    public Date getProjetDteCloture() {
        return projetDteCloture;
    }

    public void setProjetDteCloture(Date projetDteCloture) {
        this.projetDteCloture = projetDteCloture;
    }

    public String getProjetConcept() {
        return projetConcept;
    }

    public void setProjetConcept(String projetConcept) {
        this.projetConcept = projetConcept;
    }
    
    
    
    public Set<Risque> getRisques() {
        return this.risques;
    }
    
    public void setRisques(Set<Risque> risques) {
        this.risques = risques;
    }
    public Set<Demande> getDemandes() {
        return this.demandes;
    }
    
    public void setDemandes(Set<Demande> demandes) {
        this.demandes = demandes;
    }
    public Set<Sousprojet> getSousprojets() {
        return this.sousprojets;
    }
    
    public void setSousprojets(Set<Sousprojet> sousprojets) {
        this.sousprojets = sousprojets;
    }
    public Set<Pointsus> getPointsuses() {
        return this.pointsuses;
    }
    
    public void setPointsuses(Set<Pointsus> pointsuses) {
        this.pointsuses = pointsuses;
    }




}


